name: Add Preview Link Comment

on:
  push:
    branches:
      - '*'

jobs:
  add_preview_link_comment:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.email "noreply@github.com"
          git config --global user.name "github-actions"

      - name: Extract branch name
        id: branch_name
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

      - name: Generate preview link
        id: preview_link
        run: echo "##[set-output name=link;]temporal-documentation-git-${{ steps.branch_name.outputs.branch }}.preview.thundergun.io"

      - name: Append preview link to commit message
        run: |
          preview_link="${{ steps.preview_link.outputs.link }}"
          original_message="$(git log --format=%B -n 1 ${{ github.sha }})"
          new_message="${original_message}\n\nPreview Link: ${preview_link}"
          git commit --amend --no-edit -m "$new_message"

      - name: Push changes
        run: |
          git push origin HEAD:${{ github.ref }}
